// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackendData.proto

package com.noname.backend;

public final class BackendPayload {
  private BackendPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataMailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataMailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BackendData.proto\"/\n\007Request\022\023\n\013reques" +
      "tCode\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\"6\n\020DataLogi" +
      "nRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\".\n\017DataMailRequest\022\n\n\002to\030\001 \001(\t\022\017\n\007c" +
      "ontent\030\002 \001(\t\"@\n\010Response\022\016\n\006result\030\001 \001(\005" +
      "\022\023\n\013requestCode\030\002 \001(\005\022\017\n\007content\030\003 \001(\t\"\030" +
      "\n\010DataPing\022\014\n\004time\030\001 \001(\003\"\030\n\010DataPong\022\014\n\004" +
      "time\030\001 \001(\003\"\326\002\n\007Payload\022!\n\013payloadType\030\001 " +
      "\001(\0162\014.PayloadType\022\033\n\007request\030\002 \001(\0132\010.Req" +
      "uestH\000\022\035\n\010response\030\003 \001(\0132\t.ResponseH\001\022)\n" +
      "\014loginRequest\030\004 \001(\0132\021.DataLoginRequestH\002" +
      "\022\'\n\013mailRequest\030\005 \001(\0132\020.DataMailRequestH" +
      "\003\022\031\n\004ping\030\006 \001(\0132\t.DataPingH\004\022\031\n\004pong\030\007 \001" +
      "(\0132\t.DataPingH\005B\020\n\016simple_requestB\021\n\017sim" +
      "ple_responseB\022\n\020DataLoginRequestB\021\n\017Data" +
      "MailRequestB\n\n\010DataPingB\n\n\010DataPong*o\n\013P" +
      "ayloadType\022\020\n\014BASE_REQUEST\020\000\022\021\n\rBASE_RES" +
      "PONSE\020\001\022\016\n\nAUTH_LOGIN\020\002\022\r\n\tBASE_PING\020\003\022\r" +
      "\n\tBASE_PONG\020\004\022\r\n\tUSER_MAIL\020dB&\n\022com.nona" +
      "me.backendB\016BackendPayloadP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "RequestCode", "Content", });
    internal_static_DataLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataLoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_DataMailRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DataMailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataMailRequest_descriptor,
        new java.lang.String[] { "To", "Content", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Result", "RequestCode", "Content", });
    internal_static_DataPing_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DataPing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPing_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_DataPong_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_DataPong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPong_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new java.lang.String[] { "PayloadType", "Request", "Response", "LoginRequest", "MailRequest", "Ping", "Pong", "SimpleRequest", "SimpleResponse", "DataLoginRequest", "DataMailRequest", "DataPing", "DataPong", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
