// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackendData.proto

package com.noname.backend;

public interface DataMailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataMailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string to = 1;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 1;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
