// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackendData.proto

package com.noname.backend;

public interface DataPongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataPong)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   */
  long getTime();
}
