// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackendData.proto

package com.noname.backend;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PayloadType payloadType = 1;</code>
   */
  int getPayloadTypeValue();
  /**
   * <code>.PayloadType payloadType = 1;</code>
   */
  com.noname.backend.PayloadType getPayloadType();

  /**
   * <code>.Request request = 2;</code>
   */
  boolean hasRequest();
  /**
   * <code>.Request request = 2;</code>
   */
  com.noname.backend.Request getRequest();
  /**
   * <code>.Request request = 2;</code>
   */
  com.noname.backend.RequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.Response response = 3;</code>
   */
  boolean hasResponse();
  /**
   * <code>.Response response = 3;</code>
   */
  com.noname.backend.Response getResponse();
  /**
   * <code>.Response response = 3;</code>
   */
  com.noname.backend.ResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>.DataLoginRequest loginRequest = 4;</code>
   */
  boolean hasLoginRequest();
  /**
   * <code>.DataLoginRequest loginRequest = 4;</code>
   */
  com.noname.backend.DataLoginRequest getLoginRequest();
  /**
   * <code>.DataLoginRequest loginRequest = 4;</code>
   */
  com.noname.backend.DataLoginRequestOrBuilder getLoginRequestOrBuilder();

  /**
   * <code>.DataMailRequest mailRequest = 5;</code>
   */
  boolean hasMailRequest();
  /**
   * <code>.DataMailRequest mailRequest = 5;</code>
   */
  com.noname.backend.DataMailRequest getMailRequest();
  /**
   * <code>.DataMailRequest mailRequest = 5;</code>
   */
  com.noname.backend.DataMailRequestOrBuilder getMailRequestOrBuilder();

  /**
   * <code>.DataPing ping = 6;</code>
   */
  boolean hasPing();
  /**
   * <code>.DataPing ping = 6;</code>
   */
  com.noname.backend.DataPing getPing();
  /**
   * <code>.DataPing ping = 6;</code>
   */
  com.noname.backend.DataPingOrBuilder getPingOrBuilder();

  /**
   * <code>.DataPing pong = 7;</code>
   */
  boolean hasPong();
  /**
   * <code>.DataPing pong = 7;</code>
   */
  com.noname.backend.DataPing getPong();
  /**
   * <code>.DataPing pong = 7;</code>
   */
  com.noname.backend.DataPingOrBuilder getPongOrBuilder();

  public com.noname.backend.Payload.SimpleRequestCase getSimpleRequestCase();

  public com.noname.backend.Payload.SimpleResponseCase getSimpleResponseCase();

  public com.noname.backend.Payload.DataLoginRequestCase getDataLoginRequestCase();

  public com.noname.backend.Payload.DataMailRequestCase getDataMailRequestCase();

  public com.noname.backend.Payload.DataPingCase getDataPingCase();

  public com.noname.backend.Payload.DataPongCase getDataPongCase();
}
