// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackendData.proto

package com.noname.backend;

/**
 * Protobuf type {@code Payload}
 */
public  final class Payload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Payload)
    PayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Payload.newBuilder() to construct.
  private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payload() {
    payloadType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Payload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            payloadType_ = rawValue;
            break;
          }
          case 18: {
            com.noname.backend.Request.Builder subBuilder = null;
            if (simpleRequestCase_ == 2) {
              subBuilder = ((com.noname.backend.Request) simpleRequest_).toBuilder();
            }
            simpleRequest_ =
                input.readMessage(com.noname.backend.Request.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.noname.backend.Request) simpleRequest_);
              simpleRequest_ = subBuilder.buildPartial();
            }
            simpleRequestCase_ = 2;
            break;
          }
          case 26: {
            com.noname.backend.Response.Builder subBuilder = null;
            if (simpleResponseCase_ == 3) {
              subBuilder = ((com.noname.backend.Response) simpleResponse_).toBuilder();
            }
            simpleResponse_ =
                input.readMessage(com.noname.backend.Response.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.noname.backend.Response) simpleResponse_);
              simpleResponse_ = subBuilder.buildPartial();
            }
            simpleResponseCase_ = 3;
            break;
          }
          case 34: {
            com.noname.backend.DataLoginRequest.Builder subBuilder = null;
            if (dataLoginRequestCase_ == 4) {
              subBuilder = ((com.noname.backend.DataLoginRequest) dataLoginRequest_).toBuilder();
            }
            dataLoginRequest_ =
                input.readMessage(com.noname.backend.DataLoginRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.noname.backend.DataLoginRequest) dataLoginRequest_);
              dataLoginRequest_ = subBuilder.buildPartial();
            }
            dataLoginRequestCase_ = 4;
            break;
          }
          case 42: {
            com.noname.backend.DataMailRequest.Builder subBuilder = null;
            if (dataMailRequestCase_ == 5) {
              subBuilder = ((com.noname.backend.DataMailRequest) dataMailRequest_).toBuilder();
            }
            dataMailRequest_ =
                input.readMessage(com.noname.backend.DataMailRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.noname.backend.DataMailRequest) dataMailRequest_);
              dataMailRequest_ = subBuilder.buildPartial();
            }
            dataMailRequestCase_ = 5;
            break;
          }
          case 50: {
            com.noname.backend.DataPing.Builder subBuilder = null;
            if (dataPingCase_ == 6) {
              subBuilder = ((com.noname.backend.DataPing) dataPing_).toBuilder();
            }
            dataPing_ =
                input.readMessage(com.noname.backend.DataPing.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.noname.backend.DataPing) dataPing_);
              dataPing_ = subBuilder.buildPartial();
            }
            dataPingCase_ = 6;
            break;
          }
          case 58: {
            com.noname.backend.DataPing.Builder subBuilder = null;
            if (dataPongCase_ == 7) {
              subBuilder = ((com.noname.backend.DataPing) dataPong_).toBuilder();
            }
            dataPong_ =
                input.readMessage(com.noname.backend.DataPing.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.noname.backend.DataPing) dataPong_);
              dataPong_ = subBuilder.buildPartial();
            }
            dataPongCase_ = 7;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.noname.backend.BackendPayload.internal_static_Payload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.noname.backend.BackendPayload.internal_static_Payload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.noname.backend.Payload.class, com.noname.backend.Payload.Builder.class);
  }

  private int simpleRequestCase_ = 0;
  private java.lang.Object simpleRequest_;
  public enum SimpleRequestCase
      implements com.google.protobuf.Internal.EnumLite {
    REQUEST(2),
    SIMPLEREQUEST_NOT_SET(0);
    private final int value;
    private SimpleRequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SimpleRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static SimpleRequestCase forNumber(int value) {
      switch (value) {
        case 2: return REQUEST;
        case 0: return SIMPLEREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SimpleRequestCase
  getSimpleRequestCase() {
    return SimpleRequestCase.forNumber(
        simpleRequestCase_);
  }

  private int simpleResponseCase_ = 0;
  private java.lang.Object simpleResponse_;
  public enum SimpleResponseCase
      implements com.google.protobuf.Internal.EnumLite {
    RESPONSE(3),
    SIMPLERESPONSE_NOT_SET(0);
    private final int value;
    private SimpleResponseCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SimpleResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static SimpleResponseCase forNumber(int value) {
      switch (value) {
        case 3: return RESPONSE;
        case 0: return SIMPLERESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SimpleResponseCase
  getSimpleResponseCase() {
    return SimpleResponseCase.forNumber(
        simpleResponseCase_);
  }

  private int dataLoginRequestCase_ = 0;
  private java.lang.Object dataLoginRequest_;
  public enum DataLoginRequestCase
      implements com.google.protobuf.Internal.EnumLite {
    LOGINREQUEST(4),
    DATALOGINREQUEST_NOT_SET(0);
    private final int value;
    private DataLoginRequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataLoginRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataLoginRequestCase forNumber(int value) {
      switch (value) {
        case 4: return LOGINREQUEST;
        case 0: return DATALOGINREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataLoginRequestCase
  getDataLoginRequestCase() {
    return DataLoginRequestCase.forNumber(
        dataLoginRequestCase_);
  }

  private int dataMailRequestCase_ = 0;
  private java.lang.Object dataMailRequest_;
  public enum DataMailRequestCase
      implements com.google.protobuf.Internal.EnumLite {
    MAILREQUEST(5),
    DATAMAILREQUEST_NOT_SET(0);
    private final int value;
    private DataMailRequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataMailRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataMailRequestCase forNumber(int value) {
      switch (value) {
        case 5: return MAILREQUEST;
        case 0: return DATAMAILREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataMailRequestCase
  getDataMailRequestCase() {
    return DataMailRequestCase.forNumber(
        dataMailRequestCase_);
  }

  private int dataPingCase_ = 0;
  private java.lang.Object dataPing_;
  public enum DataPingCase
      implements com.google.protobuf.Internal.EnumLite {
    PING(6),
    DATAPING_NOT_SET(0);
    private final int value;
    private DataPingCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataPingCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataPingCase forNumber(int value) {
      switch (value) {
        case 6: return PING;
        case 0: return DATAPING_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataPingCase
  getDataPingCase() {
    return DataPingCase.forNumber(
        dataPingCase_);
  }

  private int dataPongCase_ = 0;
  private java.lang.Object dataPong_;
  public enum DataPongCase
      implements com.google.protobuf.Internal.EnumLite {
    PONG(7),
    DATAPONG_NOT_SET(0);
    private final int value;
    private DataPongCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataPongCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataPongCase forNumber(int value) {
      switch (value) {
        case 7: return PONG;
        case 0: return DATAPONG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataPongCase
  getDataPongCase() {
    return DataPongCase.forNumber(
        dataPongCase_);
  }

  public static final int PAYLOADTYPE_FIELD_NUMBER = 1;
  private int payloadType_;
  /**
   * <code>.PayloadType payloadType = 1;</code>
   */
  public int getPayloadTypeValue() {
    return payloadType_;
  }
  /**
   * <code>.PayloadType payloadType = 1;</code>
   */
  public com.noname.backend.PayloadType getPayloadType() {
    @SuppressWarnings("deprecation")
    com.noname.backend.PayloadType result = com.noname.backend.PayloadType.valueOf(payloadType_);
    return result == null ? com.noname.backend.PayloadType.UNRECOGNIZED : result;
  }

  public static final int REQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.Request request = 2;</code>
   */
  public boolean hasRequest() {
    return simpleRequestCase_ == 2;
  }
  /**
   * <code>.Request request = 2;</code>
   */
  public com.noname.backend.Request getRequest() {
    if (simpleRequestCase_ == 2) {
       return (com.noname.backend.Request) simpleRequest_;
    }
    return com.noname.backend.Request.getDefaultInstance();
  }
  /**
   * <code>.Request request = 2;</code>
   */
  public com.noname.backend.RequestOrBuilder getRequestOrBuilder() {
    if (simpleRequestCase_ == 2) {
       return (com.noname.backend.Request) simpleRequest_;
    }
    return com.noname.backend.Request.getDefaultInstance();
  }

  public static final int RESPONSE_FIELD_NUMBER = 3;
  /**
   * <code>.Response response = 3;</code>
   */
  public boolean hasResponse() {
    return simpleResponseCase_ == 3;
  }
  /**
   * <code>.Response response = 3;</code>
   */
  public com.noname.backend.Response getResponse() {
    if (simpleResponseCase_ == 3) {
       return (com.noname.backend.Response) simpleResponse_;
    }
    return com.noname.backend.Response.getDefaultInstance();
  }
  /**
   * <code>.Response response = 3;</code>
   */
  public com.noname.backend.ResponseOrBuilder getResponseOrBuilder() {
    if (simpleResponseCase_ == 3) {
       return (com.noname.backend.Response) simpleResponse_;
    }
    return com.noname.backend.Response.getDefaultInstance();
  }

  public static final int LOGINREQUEST_FIELD_NUMBER = 4;
  /**
   * <code>.DataLoginRequest loginRequest = 4;</code>
   */
  public boolean hasLoginRequest() {
    return dataLoginRequestCase_ == 4;
  }
  /**
   * <code>.DataLoginRequest loginRequest = 4;</code>
   */
  public com.noname.backend.DataLoginRequest getLoginRequest() {
    if (dataLoginRequestCase_ == 4) {
       return (com.noname.backend.DataLoginRequest) dataLoginRequest_;
    }
    return com.noname.backend.DataLoginRequest.getDefaultInstance();
  }
  /**
   * <code>.DataLoginRequest loginRequest = 4;</code>
   */
  public com.noname.backend.DataLoginRequestOrBuilder getLoginRequestOrBuilder() {
    if (dataLoginRequestCase_ == 4) {
       return (com.noname.backend.DataLoginRequest) dataLoginRequest_;
    }
    return com.noname.backend.DataLoginRequest.getDefaultInstance();
  }

  public static final int MAILREQUEST_FIELD_NUMBER = 5;
  /**
   * <code>.DataMailRequest mailRequest = 5;</code>
   */
  public boolean hasMailRequest() {
    return dataMailRequestCase_ == 5;
  }
  /**
   * <code>.DataMailRequest mailRequest = 5;</code>
   */
  public com.noname.backend.DataMailRequest getMailRequest() {
    if (dataMailRequestCase_ == 5) {
       return (com.noname.backend.DataMailRequest) dataMailRequest_;
    }
    return com.noname.backend.DataMailRequest.getDefaultInstance();
  }
  /**
   * <code>.DataMailRequest mailRequest = 5;</code>
   */
  public com.noname.backend.DataMailRequestOrBuilder getMailRequestOrBuilder() {
    if (dataMailRequestCase_ == 5) {
       return (com.noname.backend.DataMailRequest) dataMailRequest_;
    }
    return com.noname.backend.DataMailRequest.getDefaultInstance();
  }

  public static final int PING_FIELD_NUMBER = 6;
  /**
   * <code>.DataPing ping = 6;</code>
   */
  public boolean hasPing() {
    return dataPingCase_ == 6;
  }
  /**
   * <code>.DataPing ping = 6;</code>
   */
  public com.noname.backend.DataPing getPing() {
    if (dataPingCase_ == 6) {
       return (com.noname.backend.DataPing) dataPing_;
    }
    return com.noname.backend.DataPing.getDefaultInstance();
  }
  /**
   * <code>.DataPing ping = 6;</code>
   */
  public com.noname.backend.DataPingOrBuilder getPingOrBuilder() {
    if (dataPingCase_ == 6) {
       return (com.noname.backend.DataPing) dataPing_;
    }
    return com.noname.backend.DataPing.getDefaultInstance();
  }

  public static final int PONG_FIELD_NUMBER = 7;
  /**
   * <code>.DataPing pong = 7;</code>
   */
  public boolean hasPong() {
    return dataPongCase_ == 7;
  }
  /**
   * <code>.DataPing pong = 7;</code>
   */
  public com.noname.backend.DataPing getPong() {
    if (dataPongCase_ == 7) {
       return (com.noname.backend.DataPing) dataPong_;
    }
    return com.noname.backend.DataPing.getDefaultInstance();
  }
  /**
   * <code>.DataPing pong = 7;</code>
   */
  public com.noname.backend.DataPingOrBuilder getPongOrBuilder() {
    if (dataPongCase_ == 7) {
       return (com.noname.backend.DataPing) dataPong_;
    }
    return com.noname.backend.DataPing.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadType_ != com.noname.backend.PayloadType.BASE_REQUEST.getNumber()) {
      output.writeEnum(1, payloadType_);
    }
    if (simpleRequestCase_ == 2) {
      output.writeMessage(2, (com.noname.backend.Request) simpleRequest_);
    }
    if (simpleResponseCase_ == 3) {
      output.writeMessage(3, (com.noname.backend.Response) simpleResponse_);
    }
    if (dataLoginRequestCase_ == 4) {
      output.writeMessage(4, (com.noname.backend.DataLoginRequest) dataLoginRequest_);
    }
    if (dataMailRequestCase_ == 5) {
      output.writeMessage(5, (com.noname.backend.DataMailRequest) dataMailRequest_);
    }
    if (dataPingCase_ == 6) {
      output.writeMessage(6, (com.noname.backend.DataPing) dataPing_);
    }
    if (dataPongCase_ == 7) {
      output.writeMessage(7, (com.noname.backend.DataPing) dataPong_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadType_ != com.noname.backend.PayloadType.BASE_REQUEST.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, payloadType_);
    }
    if (simpleRequestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.noname.backend.Request) simpleRequest_);
    }
    if (simpleResponseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.noname.backend.Response) simpleResponse_);
    }
    if (dataLoginRequestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.noname.backend.DataLoginRequest) dataLoginRequest_);
    }
    if (dataMailRequestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.noname.backend.DataMailRequest) dataMailRequest_);
    }
    if (dataPingCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.noname.backend.DataPing) dataPing_);
    }
    if (dataPongCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.noname.backend.DataPing) dataPong_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.noname.backend.Payload)) {
      return super.equals(obj);
    }
    com.noname.backend.Payload other = (com.noname.backend.Payload) obj;

    boolean result = true;
    result = result && payloadType_ == other.payloadType_;
    result = result && getSimpleRequestCase().equals(
        other.getSimpleRequestCase());
    if (!result) return false;
    switch (simpleRequestCase_) {
      case 2:
        result = result && getRequest()
            .equals(other.getRequest());
        break;
      case 0:
      default:
    }
    result = result && getSimpleResponseCase().equals(
        other.getSimpleResponseCase());
    if (!result) return false;
    switch (simpleResponseCase_) {
      case 3:
        result = result && getResponse()
            .equals(other.getResponse());
        break;
      case 0:
      default:
    }
    result = result && getDataLoginRequestCase().equals(
        other.getDataLoginRequestCase());
    if (!result) return false;
    switch (dataLoginRequestCase_) {
      case 4:
        result = result && getLoginRequest()
            .equals(other.getLoginRequest());
        break;
      case 0:
      default:
    }
    result = result && getDataMailRequestCase().equals(
        other.getDataMailRequestCase());
    if (!result) return false;
    switch (dataMailRequestCase_) {
      case 5:
        result = result && getMailRequest()
            .equals(other.getMailRequest());
        break;
      case 0:
      default:
    }
    result = result && getDataPingCase().equals(
        other.getDataPingCase());
    if (!result) return false;
    switch (dataPingCase_) {
      case 6:
        result = result && getPing()
            .equals(other.getPing());
        break;
      case 0:
      default:
    }
    result = result && getDataPongCase().equals(
        other.getDataPongCase());
    if (!result) return false;
    switch (dataPongCase_) {
      case 7:
        result = result && getPong()
            .equals(other.getPong());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAYLOADTYPE_FIELD_NUMBER;
    hash = (53 * hash) + payloadType_;
    switch (simpleRequestCase_) {
      case 2:
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
        break;
      case 0:
      default:
    }
    switch (simpleResponseCase_) {
      case 3:
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
        break;
      case 0:
      default:
    }
    switch (dataLoginRequestCase_) {
      case 4:
        hash = (37 * hash) + LOGINREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getLoginRequest().hashCode();
        break;
      case 0:
      default:
    }
    switch (dataMailRequestCase_) {
      case 5:
        hash = (37 * hash) + MAILREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getMailRequest().hashCode();
        break;
      case 0:
      default:
    }
    switch (dataPingCase_) {
      case 6:
        hash = (37 * hash) + PING_FIELD_NUMBER;
        hash = (53 * hash) + getPing().hashCode();
        break;
      case 0:
      default:
    }
    switch (dataPongCase_) {
      case 7:
        hash = (37 * hash) + PONG_FIELD_NUMBER;
        hash = (53 * hash) + getPong().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.noname.backend.Payload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.noname.backend.Payload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.noname.backend.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.noname.backend.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.noname.backend.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.noname.backend.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.noname.backend.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.noname.backend.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.noname.backend.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.noname.backend.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.noname.backend.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.noname.backend.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.noname.backend.Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Payload)
      com.noname.backend.PayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.noname.backend.BackendPayload.internal_static_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.noname.backend.BackendPayload.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.noname.backend.Payload.class, com.noname.backend.Payload.Builder.class);
    }

    // Construct using com.noname.backend.Payload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      payloadType_ = 0;

      simpleRequestCase_ = 0;
      simpleRequest_ = null;
      simpleResponseCase_ = 0;
      simpleResponse_ = null;
      dataLoginRequestCase_ = 0;
      dataLoginRequest_ = null;
      dataMailRequestCase_ = 0;
      dataMailRequest_ = null;
      dataPingCase_ = 0;
      dataPing_ = null;
      dataPongCase_ = 0;
      dataPong_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.noname.backend.BackendPayload.internal_static_Payload_descriptor;
    }

    @java.lang.Override
    public com.noname.backend.Payload getDefaultInstanceForType() {
      return com.noname.backend.Payload.getDefaultInstance();
    }

    @java.lang.Override
    public com.noname.backend.Payload build() {
      com.noname.backend.Payload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.noname.backend.Payload buildPartial() {
      com.noname.backend.Payload result = new com.noname.backend.Payload(this);
      result.payloadType_ = payloadType_;
      if (simpleRequestCase_ == 2) {
        if (requestBuilder_ == null) {
          result.simpleRequest_ = simpleRequest_;
        } else {
          result.simpleRequest_ = requestBuilder_.build();
        }
      }
      if (simpleResponseCase_ == 3) {
        if (responseBuilder_ == null) {
          result.simpleResponse_ = simpleResponse_;
        } else {
          result.simpleResponse_ = responseBuilder_.build();
        }
      }
      if (dataLoginRequestCase_ == 4) {
        if (loginRequestBuilder_ == null) {
          result.dataLoginRequest_ = dataLoginRequest_;
        } else {
          result.dataLoginRequest_ = loginRequestBuilder_.build();
        }
      }
      if (dataMailRequestCase_ == 5) {
        if (mailRequestBuilder_ == null) {
          result.dataMailRequest_ = dataMailRequest_;
        } else {
          result.dataMailRequest_ = mailRequestBuilder_.build();
        }
      }
      if (dataPingCase_ == 6) {
        if (pingBuilder_ == null) {
          result.dataPing_ = dataPing_;
        } else {
          result.dataPing_ = pingBuilder_.build();
        }
      }
      if (dataPongCase_ == 7) {
        if (pongBuilder_ == null) {
          result.dataPong_ = dataPong_;
        } else {
          result.dataPong_ = pongBuilder_.build();
        }
      }
      result.simpleRequestCase_ = simpleRequestCase_;
      result.simpleResponseCase_ = simpleResponseCase_;
      result.dataLoginRequestCase_ = dataLoginRequestCase_;
      result.dataMailRequestCase_ = dataMailRequestCase_;
      result.dataPingCase_ = dataPingCase_;
      result.dataPongCase_ = dataPongCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.noname.backend.Payload) {
        return mergeFrom((com.noname.backend.Payload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.noname.backend.Payload other) {
      if (other == com.noname.backend.Payload.getDefaultInstance()) return this;
      if (other.payloadType_ != 0) {
        setPayloadTypeValue(other.getPayloadTypeValue());
      }
      switch (other.getSimpleRequestCase()) {
        case REQUEST: {
          mergeRequest(other.getRequest());
          break;
        }
        case SIMPLEREQUEST_NOT_SET: {
          break;
        }
      }
      switch (other.getSimpleResponseCase()) {
        case RESPONSE: {
          mergeResponse(other.getResponse());
          break;
        }
        case SIMPLERESPONSE_NOT_SET: {
          break;
        }
      }
      switch (other.getDataLoginRequestCase()) {
        case LOGINREQUEST: {
          mergeLoginRequest(other.getLoginRequest());
          break;
        }
        case DATALOGINREQUEST_NOT_SET: {
          break;
        }
      }
      switch (other.getDataMailRequestCase()) {
        case MAILREQUEST: {
          mergeMailRequest(other.getMailRequest());
          break;
        }
        case DATAMAILREQUEST_NOT_SET: {
          break;
        }
      }
      switch (other.getDataPingCase()) {
        case PING: {
          mergePing(other.getPing());
          break;
        }
        case DATAPING_NOT_SET: {
          break;
        }
      }
      switch (other.getDataPongCase()) {
        case PONG: {
          mergePong(other.getPong());
          break;
        }
        case DATAPONG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.noname.backend.Payload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.noname.backend.Payload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int simpleRequestCase_ = 0;
    private java.lang.Object simpleRequest_;
    public SimpleRequestCase
        getSimpleRequestCase() {
      return SimpleRequestCase.forNumber(
          simpleRequestCase_);
    }

    public Builder clearSimpleRequest() {
      simpleRequestCase_ = 0;
      simpleRequest_ = null;
      onChanged();
      return this;
    }

    private int simpleResponseCase_ = 0;
    private java.lang.Object simpleResponse_;
    public SimpleResponseCase
        getSimpleResponseCase() {
      return SimpleResponseCase.forNumber(
          simpleResponseCase_);
    }

    public Builder clearSimpleResponse() {
      simpleResponseCase_ = 0;
      simpleResponse_ = null;
      onChanged();
      return this;
    }

    private int dataLoginRequestCase_ = 0;
    private java.lang.Object dataLoginRequest_;
    public DataLoginRequestCase
        getDataLoginRequestCase() {
      return DataLoginRequestCase.forNumber(
          dataLoginRequestCase_);
    }

    public Builder clearDataLoginRequest() {
      dataLoginRequestCase_ = 0;
      dataLoginRequest_ = null;
      onChanged();
      return this;
    }

    private int dataMailRequestCase_ = 0;
    private java.lang.Object dataMailRequest_;
    public DataMailRequestCase
        getDataMailRequestCase() {
      return DataMailRequestCase.forNumber(
          dataMailRequestCase_);
    }

    public Builder clearDataMailRequest() {
      dataMailRequestCase_ = 0;
      dataMailRequest_ = null;
      onChanged();
      return this;
    }

    private int dataPingCase_ = 0;
    private java.lang.Object dataPing_;
    public DataPingCase
        getDataPingCase() {
      return DataPingCase.forNumber(
          dataPingCase_);
    }

    public Builder clearDataPing() {
      dataPingCase_ = 0;
      dataPing_ = null;
      onChanged();
      return this;
    }

    private int dataPongCase_ = 0;
    private java.lang.Object dataPong_;
    public DataPongCase
        getDataPongCase() {
      return DataPongCase.forNumber(
          dataPongCase_);
    }

    public Builder clearDataPong() {
      dataPongCase_ = 0;
      dataPong_ = null;
      onChanged();
      return this;
    }


    private int payloadType_ = 0;
    /**
     * <code>.PayloadType payloadType = 1;</code>
     */
    public int getPayloadTypeValue() {
      return payloadType_;
    }
    /**
     * <code>.PayloadType payloadType = 1;</code>
     */
    public Builder setPayloadTypeValue(int value) {
      payloadType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.PayloadType payloadType = 1;</code>
     */
    public com.noname.backend.PayloadType getPayloadType() {
      @SuppressWarnings("deprecation")
      com.noname.backend.PayloadType result = com.noname.backend.PayloadType.valueOf(payloadType_);
      return result == null ? com.noname.backend.PayloadType.UNRECOGNIZED : result;
    }
    /**
     * <code>.PayloadType payloadType = 1;</code>
     */
    public Builder setPayloadType(com.noname.backend.PayloadType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      payloadType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.PayloadType payloadType = 1;</code>
     */
    public Builder clearPayloadType() {
      
      payloadType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.Request, com.noname.backend.Request.Builder, com.noname.backend.RequestOrBuilder> requestBuilder_;
    /**
     * <code>.Request request = 2;</code>
     */
    public boolean hasRequest() {
      return simpleRequestCase_ == 2;
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public com.noname.backend.Request getRequest() {
      if (requestBuilder_ == null) {
        if (simpleRequestCase_ == 2) {
          return (com.noname.backend.Request) simpleRequest_;
        }
        return com.noname.backend.Request.getDefaultInstance();
      } else {
        if (simpleRequestCase_ == 2) {
          return requestBuilder_.getMessage();
        }
        return com.noname.backend.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public Builder setRequest(com.noname.backend.Request value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        simpleRequest_ = value;
        onChanged();
      } else {
        requestBuilder_.setMessage(value);
      }
      simpleRequestCase_ = 2;
      return this;
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public Builder setRequest(
        com.noname.backend.Request.Builder builderForValue) {
      if (requestBuilder_ == null) {
        simpleRequest_ = builderForValue.build();
        onChanged();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      simpleRequestCase_ = 2;
      return this;
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public Builder mergeRequest(com.noname.backend.Request value) {
      if (requestBuilder_ == null) {
        if (simpleRequestCase_ == 2 &&
            simpleRequest_ != com.noname.backend.Request.getDefaultInstance()) {
          simpleRequest_ = com.noname.backend.Request.newBuilder((com.noname.backend.Request) simpleRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          simpleRequest_ = value;
        }
        onChanged();
      } else {
        if (simpleRequestCase_ == 2) {
          requestBuilder_.mergeFrom(value);
        }
        requestBuilder_.setMessage(value);
      }
      simpleRequestCase_ = 2;
      return this;
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        if (simpleRequestCase_ == 2) {
          simpleRequestCase_ = 0;
          simpleRequest_ = null;
          onChanged();
        }
      } else {
        if (simpleRequestCase_ == 2) {
          simpleRequestCase_ = 0;
          simpleRequest_ = null;
        }
        requestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public com.noname.backend.Request.Builder getRequestBuilder() {
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.Request request = 2;</code>
     */
    public com.noname.backend.RequestOrBuilder getRequestOrBuilder() {
      if ((simpleRequestCase_ == 2) && (requestBuilder_ != null)) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        if (simpleRequestCase_ == 2) {
          return (com.noname.backend.Request) simpleRequest_;
        }
        return com.noname.backend.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.Request request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.Request, com.noname.backend.Request.Builder, com.noname.backend.RequestOrBuilder> 
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        if (!(simpleRequestCase_ == 2)) {
          simpleRequest_ = com.noname.backend.Request.getDefaultInstance();
        }
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.noname.backend.Request, com.noname.backend.Request.Builder, com.noname.backend.RequestOrBuilder>(
                (com.noname.backend.Request) simpleRequest_,
                getParentForChildren(),
                isClean());
        simpleRequest_ = null;
      }
      simpleRequestCase_ = 2;
      onChanged();;
      return requestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.Response, com.noname.backend.Response.Builder, com.noname.backend.ResponseOrBuilder> responseBuilder_;
    /**
     * <code>.Response response = 3;</code>
     */
    public boolean hasResponse() {
      return simpleResponseCase_ == 3;
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public com.noname.backend.Response getResponse() {
      if (responseBuilder_ == null) {
        if (simpleResponseCase_ == 3) {
          return (com.noname.backend.Response) simpleResponse_;
        }
        return com.noname.backend.Response.getDefaultInstance();
      } else {
        if (simpleResponseCase_ == 3) {
          return responseBuilder_.getMessage();
        }
        return com.noname.backend.Response.getDefaultInstance();
      }
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public Builder setResponse(com.noname.backend.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        simpleResponse_ = value;
        onChanged();
      } else {
        responseBuilder_.setMessage(value);
      }
      simpleResponseCase_ = 3;
      return this;
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public Builder setResponse(
        com.noname.backend.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        simpleResponse_ = builderForValue.build();
        onChanged();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      simpleResponseCase_ = 3;
      return this;
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public Builder mergeResponse(com.noname.backend.Response value) {
      if (responseBuilder_ == null) {
        if (simpleResponseCase_ == 3 &&
            simpleResponse_ != com.noname.backend.Response.getDefaultInstance()) {
          simpleResponse_ = com.noname.backend.Response.newBuilder((com.noname.backend.Response) simpleResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          simpleResponse_ = value;
        }
        onChanged();
      } else {
        if (simpleResponseCase_ == 3) {
          responseBuilder_.mergeFrom(value);
        }
        responseBuilder_.setMessage(value);
      }
      simpleResponseCase_ = 3;
      return this;
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        if (simpleResponseCase_ == 3) {
          simpleResponseCase_ = 0;
          simpleResponse_ = null;
          onChanged();
        }
      } else {
        if (simpleResponseCase_ == 3) {
          simpleResponseCase_ = 0;
          simpleResponse_ = null;
        }
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public com.noname.backend.Response.Builder getResponseBuilder() {
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.Response response = 3;</code>
     */
    public com.noname.backend.ResponseOrBuilder getResponseOrBuilder() {
      if ((simpleResponseCase_ == 3) && (responseBuilder_ != null)) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        if (simpleResponseCase_ == 3) {
          return (com.noname.backend.Response) simpleResponse_;
        }
        return com.noname.backend.Response.getDefaultInstance();
      }
    }
    /**
     * <code>.Response response = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.Response, com.noname.backend.Response.Builder, com.noname.backend.ResponseOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        if (!(simpleResponseCase_ == 3)) {
          simpleResponse_ = com.noname.backend.Response.getDefaultInstance();
        }
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.noname.backend.Response, com.noname.backend.Response.Builder, com.noname.backend.ResponseOrBuilder>(
                (com.noname.backend.Response) simpleResponse_,
                getParentForChildren(),
                isClean());
        simpleResponse_ = null;
      }
      simpleResponseCase_ = 3;
      onChanged();;
      return responseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataLoginRequest, com.noname.backend.DataLoginRequest.Builder, com.noname.backend.DataLoginRequestOrBuilder> loginRequestBuilder_;
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public boolean hasLoginRequest() {
      return dataLoginRequestCase_ == 4;
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public com.noname.backend.DataLoginRequest getLoginRequest() {
      if (loginRequestBuilder_ == null) {
        if (dataLoginRequestCase_ == 4) {
          return (com.noname.backend.DataLoginRequest) dataLoginRequest_;
        }
        return com.noname.backend.DataLoginRequest.getDefaultInstance();
      } else {
        if (dataLoginRequestCase_ == 4) {
          return loginRequestBuilder_.getMessage();
        }
        return com.noname.backend.DataLoginRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public Builder setLoginRequest(com.noname.backend.DataLoginRequest value) {
      if (loginRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataLoginRequest_ = value;
        onChanged();
      } else {
        loginRequestBuilder_.setMessage(value);
      }
      dataLoginRequestCase_ = 4;
      return this;
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public Builder setLoginRequest(
        com.noname.backend.DataLoginRequest.Builder builderForValue) {
      if (loginRequestBuilder_ == null) {
        dataLoginRequest_ = builderForValue.build();
        onChanged();
      } else {
        loginRequestBuilder_.setMessage(builderForValue.build());
      }
      dataLoginRequestCase_ = 4;
      return this;
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public Builder mergeLoginRequest(com.noname.backend.DataLoginRequest value) {
      if (loginRequestBuilder_ == null) {
        if (dataLoginRequestCase_ == 4 &&
            dataLoginRequest_ != com.noname.backend.DataLoginRequest.getDefaultInstance()) {
          dataLoginRequest_ = com.noname.backend.DataLoginRequest.newBuilder((com.noname.backend.DataLoginRequest) dataLoginRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          dataLoginRequest_ = value;
        }
        onChanged();
      } else {
        if (dataLoginRequestCase_ == 4) {
          loginRequestBuilder_.mergeFrom(value);
        }
        loginRequestBuilder_.setMessage(value);
      }
      dataLoginRequestCase_ = 4;
      return this;
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public Builder clearLoginRequest() {
      if (loginRequestBuilder_ == null) {
        if (dataLoginRequestCase_ == 4) {
          dataLoginRequestCase_ = 0;
          dataLoginRequest_ = null;
          onChanged();
        }
      } else {
        if (dataLoginRequestCase_ == 4) {
          dataLoginRequestCase_ = 0;
          dataLoginRequest_ = null;
        }
        loginRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public com.noname.backend.DataLoginRequest.Builder getLoginRequestBuilder() {
      return getLoginRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    public com.noname.backend.DataLoginRequestOrBuilder getLoginRequestOrBuilder() {
      if ((dataLoginRequestCase_ == 4) && (loginRequestBuilder_ != null)) {
        return loginRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataLoginRequestCase_ == 4) {
          return (com.noname.backend.DataLoginRequest) dataLoginRequest_;
        }
        return com.noname.backend.DataLoginRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.DataLoginRequest loginRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataLoginRequest, com.noname.backend.DataLoginRequest.Builder, com.noname.backend.DataLoginRequestOrBuilder> 
        getLoginRequestFieldBuilder() {
      if (loginRequestBuilder_ == null) {
        if (!(dataLoginRequestCase_ == 4)) {
          dataLoginRequest_ = com.noname.backend.DataLoginRequest.getDefaultInstance();
        }
        loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.noname.backend.DataLoginRequest, com.noname.backend.DataLoginRequest.Builder, com.noname.backend.DataLoginRequestOrBuilder>(
                (com.noname.backend.DataLoginRequest) dataLoginRequest_,
                getParentForChildren(),
                isClean());
        dataLoginRequest_ = null;
      }
      dataLoginRequestCase_ = 4;
      onChanged();;
      return loginRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataMailRequest, com.noname.backend.DataMailRequest.Builder, com.noname.backend.DataMailRequestOrBuilder> mailRequestBuilder_;
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public boolean hasMailRequest() {
      return dataMailRequestCase_ == 5;
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public com.noname.backend.DataMailRequest getMailRequest() {
      if (mailRequestBuilder_ == null) {
        if (dataMailRequestCase_ == 5) {
          return (com.noname.backend.DataMailRequest) dataMailRequest_;
        }
        return com.noname.backend.DataMailRequest.getDefaultInstance();
      } else {
        if (dataMailRequestCase_ == 5) {
          return mailRequestBuilder_.getMessage();
        }
        return com.noname.backend.DataMailRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public Builder setMailRequest(com.noname.backend.DataMailRequest value) {
      if (mailRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataMailRequest_ = value;
        onChanged();
      } else {
        mailRequestBuilder_.setMessage(value);
      }
      dataMailRequestCase_ = 5;
      return this;
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public Builder setMailRequest(
        com.noname.backend.DataMailRequest.Builder builderForValue) {
      if (mailRequestBuilder_ == null) {
        dataMailRequest_ = builderForValue.build();
        onChanged();
      } else {
        mailRequestBuilder_.setMessage(builderForValue.build());
      }
      dataMailRequestCase_ = 5;
      return this;
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public Builder mergeMailRequest(com.noname.backend.DataMailRequest value) {
      if (mailRequestBuilder_ == null) {
        if (dataMailRequestCase_ == 5 &&
            dataMailRequest_ != com.noname.backend.DataMailRequest.getDefaultInstance()) {
          dataMailRequest_ = com.noname.backend.DataMailRequest.newBuilder((com.noname.backend.DataMailRequest) dataMailRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          dataMailRequest_ = value;
        }
        onChanged();
      } else {
        if (dataMailRequestCase_ == 5) {
          mailRequestBuilder_.mergeFrom(value);
        }
        mailRequestBuilder_.setMessage(value);
      }
      dataMailRequestCase_ = 5;
      return this;
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public Builder clearMailRequest() {
      if (mailRequestBuilder_ == null) {
        if (dataMailRequestCase_ == 5) {
          dataMailRequestCase_ = 0;
          dataMailRequest_ = null;
          onChanged();
        }
      } else {
        if (dataMailRequestCase_ == 5) {
          dataMailRequestCase_ = 0;
          dataMailRequest_ = null;
        }
        mailRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public com.noname.backend.DataMailRequest.Builder getMailRequestBuilder() {
      return getMailRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    public com.noname.backend.DataMailRequestOrBuilder getMailRequestOrBuilder() {
      if ((dataMailRequestCase_ == 5) && (mailRequestBuilder_ != null)) {
        return mailRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataMailRequestCase_ == 5) {
          return (com.noname.backend.DataMailRequest) dataMailRequest_;
        }
        return com.noname.backend.DataMailRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.DataMailRequest mailRequest = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataMailRequest, com.noname.backend.DataMailRequest.Builder, com.noname.backend.DataMailRequestOrBuilder> 
        getMailRequestFieldBuilder() {
      if (mailRequestBuilder_ == null) {
        if (!(dataMailRequestCase_ == 5)) {
          dataMailRequest_ = com.noname.backend.DataMailRequest.getDefaultInstance();
        }
        mailRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.noname.backend.DataMailRequest, com.noname.backend.DataMailRequest.Builder, com.noname.backend.DataMailRequestOrBuilder>(
                (com.noname.backend.DataMailRequest) dataMailRequest_,
                getParentForChildren(),
                isClean());
        dataMailRequest_ = null;
      }
      dataMailRequestCase_ = 5;
      onChanged();;
      return mailRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataPing, com.noname.backend.DataPing.Builder, com.noname.backend.DataPingOrBuilder> pingBuilder_;
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public boolean hasPing() {
      return dataPingCase_ == 6;
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public com.noname.backend.DataPing getPing() {
      if (pingBuilder_ == null) {
        if (dataPingCase_ == 6) {
          return (com.noname.backend.DataPing) dataPing_;
        }
        return com.noname.backend.DataPing.getDefaultInstance();
      } else {
        if (dataPingCase_ == 6) {
          return pingBuilder_.getMessage();
        }
        return com.noname.backend.DataPing.getDefaultInstance();
      }
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public Builder setPing(com.noname.backend.DataPing value) {
      if (pingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataPing_ = value;
        onChanged();
      } else {
        pingBuilder_.setMessage(value);
      }
      dataPingCase_ = 6;
      return this;
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public Builder setPing(
        com.noname.backend.DataPing.Builder builderForValue) {
      if (pingBuilder_ == null) {
        dataPing_ = builderForValue.build();
        onChanged();
      } else {
        pingBuilder_.setMessage(builderForValue.build());
      }
      dataPingCase_ = 6;
      return this;
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public Builder mergePing(com.noname.backend.DataPing value) {
      if (pingBuilder_ == null) {
        if (dataPingCase_ == 6 &&
            dataPing_ != com.noname.backend.DataPing.getDefaultInstance()) {
          dataPing_ = com.noname.backend.DataPing.newBuilder((com.noname.backend.DataPing) dataPing_)
              .mergeFrom(value).buildPartial();
        } else {
          dataPing_ = value;
        }
        onChanged();
      } else {
        if (dataPingCase_ == 6) {
          pingBuilder_.mergeFrom(value);
        }
        pingBuilder_.setMessage(value);
      }
      dataPingCase_ = 6;
      return this;
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public Builder clearPing() {
      if (pingBuilder_ == null) {
        if (dataPingCase_ == 6) {
          dataPingCase_ = 0;
          dataPing_ = null;
          onChanged();
        }
      } else {
        if (dataPingCase_ == 6) {
          dataPingCase_ = 0;
          dataPing_ = null;
        }
        pingBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public com.noname.backend.DataPing.Builder getPingBuilder() {
      return getPingFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    public com.noname.backend.DataPingOrBuilder getPingOrBuilder() {
      if ((dataPingCase_ == 6) && (pingBuilder_ != null)) {
        return pingBuilder_.getMessageOrBuilder();
      } else {
        if (dataPingCase_ == 6) {
          return (com.noname.backend.DataPing) dataPing_;
        }
        return com.noname.backend.DataPing.getDefaultInstance();
      }
    }
    /**
     * <code>.DataPing ping = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataPing, com.noname.backend.DataPing.Builder, com.noname.backend.DataPingOrBuilder> 
        getPingFieldBuilder() {
      if (pingBuilder_ == null) {
        if (!(dataPingCase_ == 6)) {
          dataPing_ = com.noname.backend.DataPing.getDefaultInstance();
        }
        pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.noname.backend.DataPing, com.noname.backend.DataPing.Builder, com.noname.backend.DataPingOrBuilder>(
                (com.noname.backend.DataPing) dataPing_,
                getParentForChildren(),
                isClean());
        dataPing_ = null;
      }
      dataPingCase_ = 6;
      onChanged();;
      return pingBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataPing, com.noname.backend.DataPing.Builder, com.noname.backend.DataPingOrBuilder> pongBuilder_;
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public boolean hasPong() {
      return dataPongCase_ == 7;
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public com.noname.backend.DataPing getPong() {
      if (pongBuilder_ == null) {
        if (dataPongCase_ == 7) {
          return (com.noname.backend.DataPing) dataPong_;
        }
        return com.noname.backend.DataPing.getDefaultInstance();
      } else {
        if (dataPongCase_ == 7) {
          return pongBuilder_.getMessage();
        }
        return com.noname.backend.DataPing.getDefaultInstance();
      }
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public Builder setPong(com.noname.backend.DataPing value) {
      if (pongBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataPong_ = value;
        onChanged();
      } else {
        pongBuilder_.setMessage(value);
      }
      dataPongCase_ = 7;
      return this;
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public Builder setPong(
        com.noname.backend.DataPing.Builder builderForValue) {
      if (pongBuilder_ == null) {
        dataPong_ = builderForValue.build();
        onChanged();
      } else {
        pongBuilder_.setMessage(builderForValue.build());
      }
      dataPongCase_ = 7;
      return this;
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public Builder mergePong(com.noname.backend.DataPing value) {
      if (pongBuilder_ == null) {
        if (dataPongCase_ == 7 &&
            dataPong_ != com.noname.backend.DataPing.getDefaultInstance()) {
          dataPong_ = com.noname.backend.DataPing.newBuilder((com.noname.backend.DataPing) dataPong_)
              .mergeFrom(value).buildPartial();
        } else {
          dataPong_ = value;
        }
        onChanged();
      } else {
        if (dataPongCase_ == 7) {
          pongBuilder_.mergeFrom(value);
        }
        pongBuilder_.setMessage(value);
      }
      dataPongCase_ = 7;
      return this;
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public Builder clearPong() {
      if (pongBuilder_ == null) {
        if (dataPongCase_ == 7) {
          dataPongCase_ = 0;
          dataPong_ = null;
          onChanged();
        }
      } else {
        if (dataPongCase_ == 7) {
          dataPongCase_ = 0;
          dataPong_ = null;
        }
        pongBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public com.noname.backend.DataPing.Builder getPongBuilder() {
      return getPongFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    public com.noname.backend.DataPingOrBuilder getPongOrBuilder() {
      if ((dataPongCase_ == 7) && (pongBuilder_ != null)) {
        return pongBuilder_.getMessageOrBuilder();
      } else {
        if (dataPongCase_ == 7) {
          return (com.noname.backend.DataPing) dataPong_;
        }
        return com.noname.backend.DataPing.getDefaultInstance();
      }
    }
    /**
     * <code>.DataPing pong = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.noname.backend.DataPing, com.noname.backend.DataPing.Builder, com.noname.backend.DataPingOrBuilder> 
        getPongFieldBuilder() {
      if (pongBuilder_ == null) {
        if (!(dataPongCase_ == 7)) {
          dataPong_ = com.noname.backend.DataPing.getDefaultInstance();
        }
        pongBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.noname.backend.DataPing, com.noname.backend.DataPing.Builder, com.noname.backend.DataPingOrBuilder>(
                (com.noname.backend.DataPing) dataPong_,
                getParentForChildren(),
                isClean());
        dataPong_ = null;
      }
      dataPongCase_ = 7;
      onChanged();;
      return pongBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Payload)
  }

  // @@protoc_insertion_point(class_scope:Payload)
  private static final com.noname.backend.Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.noname.backend.Payload();
  }

  public static com.noname.backend.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payload>
      PARSER = new com.google.protobuf.AbstractParser<Payload>() {
    @java.lang.Override
    public Payload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Payload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Payload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.noname.backend.Payload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

